ALTER TABLE `cdr_data_details_vw` CHANGE COLUMN `CHARGING_ID` `CHARGING_ID` VARCHAR(250) NOT NULL DEFAULT '' AFTER `ULI_MNC`;


ALTER TABLE report_metadata DROP DONOR_IMSI;
ALTER TABLE `report_metadata` ADD COLUMN `DONOR_IMSI` VARCHAR(45) NULL DEFAULT NULL AFTER `BOOTSTRAP_ICCID`;